package org.explorink.gpsbridge.wallet

import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertTrue
import org.junit.Test
import java.io.ByteArrayOutputStream
import java.io.InputStream
import java.security.MessageDigest
import java.util.zip.GZIPInputStream

/**
 * **The check this whole phase rests on: the Kotlin pipeline must produce the
 * same bytes as `tools/walletgen.py`.**
 *
 * The app cannot be verified the usual way -- there is no device-side viewer in
 * this phase and no way to look at an asset -- so parity against the reference
 * implementation is the evidence. Fixtures in `src/test/resources/wallet-parity/`,
 * regenerated by `tools/wallet_parity_fixture.py`:
 *
 *     demo-a4.png       the input page: `walletgen.py --demo`, for a human
 *     demo-a4.gray.gz   the same page's raw 8-bit grey pixels, gzipped
 *     manifest.json     what walletgen wrote, verbatim
 *     files.json        per-file size, sha256 and 32-byte header, plus the run
 *
 * The page is committed rather than regenerated because it is the **input**, and
 * its text is rasterised by whatever font happens to be installed -- not
 * reproducible across machines, and not part of the pipeline. Both sides then
 * consume identical pixels, which `graySha256` proves before anything else runs.
 *
 * The test reads the raw pixels, not the PNG: `javax.imageio` is not on the
 * Android unit-test compile classpath (`android.jar` shadows the JDK's
 * `java.desktop`), and a PNG decoder written for a test would be one more thing
 * that can be wrong. `graySha256` is taken from the PNG's own pixels, so the two
 * fixture files cannot drift apart without this test failing.
 *
 * What this covers: autocontrast, the Lanczos resize at all three zoom levels,
 * Floyd-Steinberg dither, tile slicing, the native rotation, 1bpp packing, the
 * 32-byte header, the RLE sidecar, the asset and item id recipes, the page-image
 * geometry, and `manifest.json` as text.
 *
 * What it cannot cover, because there is no phone here: the decode of a real
 * JPEG, EXIF orientation off a camera, the share target, and the UI. Those are
 * emulator work -- `docs/android-wallet.md` says which were exercised and how.
 */
class WalletParityTest {

    private fun resource(name: String): InputStream =
        javaClass.classLoader!!.getResourceAsStream("wallet-parity/$name")
            ?: throw AssertionError("missing fixture wallet-parity/$name " +
                "(regenerate with tools/wallet_parity_fixture.py)")

    private fun text(name: String): String =
        resource(name).use { it.readBytes().toString(Charsets.UTF_8) }

    private fun sha256(b: ByteArray): String =
        WalletFormat.hex(MessageDigest.getInstance("SHA-256").digest(b))

    /** The fixture page, as the grayscale raster both implementations start from. */
    private fun sourcePage(): GrayImage {
        val fx = fixture()
        val w = Json.asInt(fx.source["width"])
        val h = Json.asInt(fx.source["height"])
        val px = GZIPInputStream(resource(Json.asString(fx.source["gray"]))).use {
            it.readBytes()
        }
        assertEquals("fixture pixel count", w * h, px.size)
        return GrayImage(w, h, px)
    }

    private fun InputStream.readBytes(): ByteArray {
        val out = ByteArrayOutputStream()
        val buf = ByteArray(8192)
        while (true) {
            val n = read(buf)
            if (n < 0) break
            out.write(buf, 0, n)
        }
        return out.toByteArray()
    }

    /** Everything the fixture recorded about the generator run. */
    private class Fixture(meta: Map<String, Any?>) {
        val run = Json.asMap(meta["run"])
        val source = Json.asMap(meta["source"])
        val manifestSha256 = Json.asString(meta["manifestSha256"])
        val files = Json.asList(meta["files"]).map { Json.asMap(it) }
    }

    private fun fixture(): Fixture = Fixture(Json.asMap(Json.parse(text("files.json"))))

    /**
     * Build the same item the generator built, in memory.
     *
     * Note what is NOT passed in: no expected geometry, no tile counts, no ids.
     * Only the panel, the title, the source name and the timestamp -- everything
     * else is derived, which is the point.
     */
    private fun build(fx: Fixture): Pair<WalletItem, MemoryAssetSink> {
        val panel = Panels.byName(Json.asString(fx.run["panel"]))
        val title = Json.asString(fx.run["title"])
        val name = Json.asString(fx.source["file"])
        val sink = MemoryAssetSink()
        val pipeline = WalletPipeline(panel, pageImage = fx.run["pageImage"] == true)
        val source = WalletPipeline.PageSource(
            gray = sourcePage(),
            name = name,
            dpiX = fx.source["dpiX"] as Double?,
            dpiY = fx.source["dpiY"] as Double?,
        )
        val item = pipeline.buildItem(
            itemId = WalletFormat.itemIdFor(title, listOf(name)),
            title = title,
            createdAt = Json.asString(fx.run["createdAt"]),
            sortOrder = 0,
            sources = listOf(source),
            sink = sink,
            paper = Json.asString(fx.run["paper"]),
            version = Json.asInt(fx.run["version"]),
        )
        return Pair(item, sink)
    }

    // --- the input ---------------------------------------------------------

    @Test
    fun the_fixture_page_is_the_pixels_the_generator_saw() {
        // If this fails, nothing below means anything: the two sides are looking
        // at different images and any divergence is the fixture's, not the code's.
        val fx = fixture()
        val page = sourcePage()
        assertEquals(Json.asInt(fx.source["width"]), page.width)
        assertEquals(Json.asInt(fx.source["height"]), page.height)
        assertEquals(Json.asString(fx.source["graySha256"]), sha256(page.pixels))
    }

    // --- ids ---------------------------------------------------------------

    @Test
    fun the_item_id_recipe_agrees() {
        val fx = fixture()
        val expected = Wallet.fromManifestJson(text("manifest.json")).items[0].id
        assertEquals(expected, WalletFormat.itemIdFor(
            Json.asString(fx.run["title"]), listOf(Json.asString(fx.source["file"]))))
    }

    @Test
    fun auto_paper_picks_what_the_generator_picked() {
        val fx = fixture()
        val page = sourcePage()
        val expected = Wallet.fromManifestJson(text("manifest.json")).items[0].pages[0].paper
        assertEquals(expected, WalletFormat.pickPaper(page.width, page.height,
            fx.source["dpiX"] as Double?, fx.source["dpiY"] as Double?))
    }

    // --- the assets --------------------------------------------------------

    @Test
    fun every_asset_file_is_byte_identical() {
        val fx = fixture()
        val (_, sink) = build(fx)

        var checkedDat = 0
        var checkedRle = 0
        for (f in fx.files) {
            val path = Json.asString(f["path"])
            val assetId = path.substringAfterLast('/').substringBeforeLast('.')
            val ext = path.substringAfterLast('.')
            val ours = (if (ext == "dat") sink.dat[assetId] else sink.rle[assetId])
            assertNotNull("we never produced $path", ours)
            assertEquals("$path shard", WalletFormat.shardOf(assetId), path.substringBefore('/'))
            assertEquals("$path size", Json.asInt(f["size"]), ours!!.size)
            assertEquals("$path header", Json.asString(f["header"]),
                WalletFormat.hex(ours.copyOfRange(0, WalletFormat.ASSET_HEADER_LEN)))
            assertEquals("$path sha256", Json.asString(f["sha256"]), sha256(ours))
            if (ext == "dat") checkedDat++ else checkedRle++
        }
        // 21 tiles + 3 page images, each with a .dat and an .rle.
        assertEquals(24, checkedDat)
        assertEquals(24, checkedRle)
        assertEquals("we produced assets the generator did not", checkedDat, sink.dat.size)
    }

    @Test
    fun the_manifest_is_byte_identical_as_text() {
        val fx = fixture()
        val (item, _) = build(fx)
        val wallet = Wallet(
            formatVersion = WalletFormat.MANIFEST_FORMAT_VERSION,
            walletVersion = 1,
            panelName = Json.asString(fx.run["panel"]),
            items = listOf(item))
        val ours = wallet.toManifestJson()
        assertEquals(text("manifest.json"), ours)
        assertEquals(fx.manifestSha256, sha256(ours.toByteArray(Charsets.UTF_8)))
    }

    @Test
    fun the_manifest_survives_a_round_trip_through_our_own_parser() {
        val theirs = text("manifest.json")
        assertEquals(theirs, Wallet.fromManifestJson(theirs).toManifestJson())
    }

    @Test
    fun the_sidecars_decode_back_to_the_payloads() {
        // Parity says the bytes match. This says they are also *correct*: the
        // device rebuilds a .dat out of the sidecar alone, so the sidecar has to
        // carry the payload and the header, not merely the right number of bytes.
        val fx = fixture()
        val (_, sink) = build(fx)
        for ((assetId, rle) in sink.rle) {
            val dat = sink.dat.getValue(assetId)
            val header = rle.copyOfRange(0, WalletFormat.ASSET_HEADER_LEN)
            assertEquals("$assetId header prefix",
                WalletFormat.hex(dat.copyOfRange(0, WalletFormat.ASSET_HEADER_LEN)),
                WalletFormat.hex(header))
            val payload = Rle.decode(rle.copyOfRange(WalletFormat.ASSET_HEADER_LEN, rle.size))
            assertEquals("$assetId payload length",
                dat.size - WalletFormat.ASSET_HEADER_LEN, payload.size)
            assertEquals("$assetId payload",
                sha256(dat.copyOfRange(WalletFormat.ASSET_HEADER_LEN, dat.size)),
                sha256(payload))
        }
    }

    @Test
    fun a_tile_aligned_window_of_the_page_image_is_the_tile() {
        // The page image and the tiles come out of the same dithered bitmap, so a
        // window pulled at a tile origin must equal the pre-cut tile. If this fails
        // the two outputs disagree with each other, whatever the parity says.
        val fx = fixture()
        val (item, sink) = build(fx)
        val panel = Panels.byName(Json.asString(fx.run["panel"]))
        val level = item.pages[0].levels.getValue("one_to_one")
        val pi = level.pageImage!!
        val page = sink.dat.getValue(pi.assetId)
            .copyOfRange(WalletFormat.ASSET_HEADER_LEN, WalletFormat.ASSET_HEADER_LEN + pi.rawLen)

        val pipeline = WalletPipeline(panel)
        var compared = 0
        for (tile in level.assets) {
            val (x, y) = pipeline.tileWindowOrigin(tile.col, tile.row, pi.nativeHeight)
            if (x < 0 || y < 0) continue
            if (x + panel.width > pi.nativeWidth || y + panel.height > pi.nativeHeight) continue
            val window = ByteArray(panel.assetBytes)
            for (row in 0 until panel.height) {
                System.arraycopy(page, (y + row) * pi.rowBytes + x / 8,
                    window, row * panel.rowBytes, panel.rowBytes)
            }
            assertEquals("tile (${tile.col},${tile.row})", tile.sha256, sha256(window))
            compared++
        }
        // 9 of the 16 A4 1:1 tiles lie fully inside the page extent; the rest are
        // in the white padding a page image drops.
        assertEquals(9, compared)
    }

    @Test
    fun the_page_image_geometry_matches_the_manifest() {
        val fx = fixture()
        val (item, _) = build(fx)
        val theirs = Wallet.fromManifestJson(text("manifest.json")).items[0]
        for (name in WalletFormat.LEVELS) {
            val a = item.pages[0].levels.getValue(name).pageImage
            val b = theirs.pages[0].levels.getValue(name).pageImage
            assertEquals("level $name has a page image", b != null, a != null)
            assertEquals("level $name", b, a)
        }
    }

    @Test
    fun a_wrong_pipeline_would_fail_this_test() {
        // A parity check that cannot fail is worth nothing. Break one step -- skip
        // autocontrast -- and the first asset must stop matching.
        val fx = fixture()
        val panel = Panels.byName(Json.asString(fx.run["panel"]))
        val pipeline = WalletPipeline(panel, pageImage = false)
        val mono = pipeline.levelCanvas(sourcePage(), "fit", "a4").dither()
        val wrong = mono.packNativeRegion(0, 0, panel.tileW, panel.tileH)
        val right = Wallet.fromManifestJson(text("manifest.json"))
            .items[0].pages[0].levels.getValue("fit").assets[0].sha256
        assertTrue("skipping autocontrast must change the bytes", sha256(wrong) != right)
    }
}
