package org.explorink.gpsbridge.wallet

import org.junit.Assert.assertArrayEquals
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNotEquals
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Test
import org.explorink.gpsbridge.wallet.WalletParityTest.Companion.Fixture
import org.explorink.gpsbridge.wallet.WalletParityTest.Companion.bytes
import org.explorink.gpsbridge.wallet.WalletParityTest.Companion.sha256
import org.explorink.gpsbridge.wallet.WalletParityTest.Companion.text

/**
 * **The encrypted tree, against `tools/walletgen.py --key`.**
 *
 * The fixture is `src/test/resources/wallet-parity-enc/`: the same demo page, the
 * same run parameters, one fixed test key (`key.hex`), regenerated by
 * `tools/wallet_parity_fixture.py`. What is compared, and how far byte-identity
 * goes:
 *
 *  - **Assets are byte-identical.** AES-256-CTR is deterministic given the key and
 *    the IV, and the IV is derived from the asset id and its version, so the
 *    ciphertext has exactly one correct value. Nothing is left to a random choice.
 *  - **The manifest is not byte-identical, and cannot be.** `manifest.enc` is
 *    AES-256-GCM with a **fresh 12-byte nonce per write** -- required by the format
 *    (`docs/wallet-format.md` section 11) and by GCM itself, which does not survive
 *    a nonce reused under one key. Two correct writers of identical content
 *    therefore produce different bytes on purpose. So the check is: the generator's
 *    container **decrypts to the plaintext we would write**, byte for byte, and the
 *    cleartext part of our own container carries what the format says it does.
 *    Loosening the asset check to match would have been the wrong fix; loosening
 *    the manifest check to a decrypt is what the format actually allows.
 *  - **No sidecars exist at all.** The fixture records zero `.rle` files.
 */
class WalletCryptoParityTest {

    private val fx = Fixture("wallet-parity-enc")
    private val key: ByteArray get() = WalletCrypto.keyFromHex(fx.keyHex!!)

    private fun cipher() = Aes256CtrCipher(key)

    @Test
    fun the_fixture_is_actually_an_encrypted_tree() {
        assertTrue(fx.encrypted)
        assertEquals("manifest.enc", fx.manifestName)
        assertEquals(0, fx.rleCount())
        assertNotNull("the fixture must carry its test key", fx.keyHex)
        assertEquals(WalletCrypto.KEY_LEN, key.size)
    }

    @Test
    fun every_encrypted_asset_is_byte_identical() {
        val (_, sink) = fx.build(cipher())
        var checked = 0
        for (f in fx.files) {
            val path = Json.asString(f["path"])
            assertTrue("an encrypted tree writes no sidecar: $path", path.endsWith(".dat"))
            val assetId = path.substringAfterLast('/').substringBeforeLast('.')
            val ours = sink.dat[assetId]
            assertNotNull("we never produced $path", ours)
            assertEquals("$path size", Json.asInt(f["size"]), ours!!.size)
            assertEquals("$path header", Json.asString(f["header"]),
                WalletFormat.hex(ours.copyOfRange(0, WalletFormat.ASSET_HEADER_LEN)))
            assertEquals("$path sha256", Json.asString(f["sha256"]), sha256(ours))
            checked++
        }
        assertEquals(fx.datCount(), checked)
        assertEquals("we produced assets the generator did not", checked, sink.dat.size)
        assertEquals("an encrypted tree writes no sidecars", 0, sink.rle.size)
    }

    @Test
    fun the_generators_manifest_decrypts_to_the_manifest_we_would_write() {
        val (item, _) = fx.build(cipher())
        val theirs = WalletCrypto.decryptManifest(key, bytes(fx.dir, "manifest.enc"))
        assertEquals(fx.ourManifest(item), theirs.toString(Charsets.UTF_8))
    }

    @Test
    fun the_generators_container_is_v2_and_says_the_wallet_version_in_the_clear() {
        val blob = bytes(fx.dir, "manifest.enc")
        val head = WalletCrypto.readManifestHeader(blob)
        assertEquals(2, head.version)
        assertEquals(0, head.flags)
        assertEquals(WalletCrypto.MANIFEST_HEADER_V2, head.headerLen)
        // Cleartext, so a locked card can be diffed (`docs/wallet-plan.md` 7g).
        assertEquals(1, head.walletVersion)
        val plain = WalletCrypto.decryptManifest(key, blob)
        assertEquals(head.plaintextLen, plain.size)
    }

    @Test
    fun our_container_round_trips_and_the_generator_can_read_its_shape() {
        val (item, _) = fx.build(cipher())
        val plain = fx.ourManifest(item).toByteArray(Charsets.UTF_8)
        val ours = WalletCrypto.encryptManifest(key, plain, 1)
        val theirs = bytes(fx.dir, "manifest.enc")
        // Same length, same cleartext header apart from the nonce -- and different
        // bytes, because the nonce is fresh. All three are the format working.
        assertEquals(theirs.size, ours.size)
        assertArrayEquals(theirs.copyOfRange(0, 6), ours.copyOfRange(0, 6))
        assertArrayEquals(theirs.copyOfRange(18, 26), ours.copyOfRange(18, 26))
        assertFalse("a fresh nonce must make two writes differ",
            theirs.contentEquals(ours))
        assertArrayEquals(plain, WalletCrypto.decryptManifest(key, ours))
    }

    @Test
    fun a_second_write_of_the_same_manifest_reuses_no_nonce() {
        val plain = "{}".toByteArray(Charsets.UTF_8)
        val a = WalletCrypto.encryptManifest(key, plain, 7)
        val b = WalletCrypto.encryptManifest(key, plain, 7)
        assertNotEquals(WalletFormat.hex(a.copyOfRange(6, 18)),
            WalletFormat.hex(b.copyOfRange(6, 18)))
    }

    /**
     * The ciphertext decrypts to the plaintext the **cleartext** fixture holds, which
     * is the claim that matters to a rider: the same document, the same pixels, one
     * of them readable off the card and one not.
     */
    @Test
    fun the_ciphertext_decrypts_to_the_cleartext_trees_payloads() {
        val clear = Fixture(WalletParityTest.DEFAULT)
        val (clearItem, clearSink) = clear.build()
        val (encItem, encSink) = fx.build(cipher())
        val c = cipher()

        val clearByLevel = HashMap<String, String>()
        for (name in WalletFormat.LEVELS) {
            clearByLevel[name] = clearItem.pages[0].levels.getValue(name).pageImage!!.assetId
        }
        var compared = 0
        for (name in WalletFormat.LEVELS) {
            val plainId = clearByLevel.getValue(name)
            val encId = encItem.pages[0].levels.getValue(name).pageImage!!.assetId
            // Crypto-scoped ids: the same document, the same level, two different paths.
            assertNotEquals("ids must not collide across the crypto boundary", plainId, encId)

            val plainDat = clearSink.dat.getValue(plainId)
            val encDat = encSink.dat.getValue(encId)
            val header = encDat.copyOfRange(0, WalletFormat.ASSET_HEADER_LEN)
            val opened = c.open(encId, header,
                encDat.copyOfRange(WalletFormat.ASSET_HEADER_LEN, encDat.size))
            assertArrayEquals("level $name payload",
                plainDat.copyOfRange(WalletFormat.ASSET_HEADER_LEN, plainDat.size), opened)
            compared++
        }
        assertEquals(3, compared)
    }

    @Test
    fun the_header_stays_cleartext_and_flags_bit0_is_set() {
        val (item, sink) = fx.build(cipher())
        for (name in WalletFormat.LEVELS) {
            val pi = item.pages[0].levels.getValue(name).pageImage!!
            val dat = sink.dat.getValue(pi.assetId)
            // Magic readable with no key at all.
            assertEquals("EWA1", dat.copyOfRange(0, 4).toString(Charsets.US_ASCII))
            assertEquals(WalletFormat.FLAG_ENCRYPTED,
                dat[20].toInt() and WalletFormat.FLAG_ENCRYPTED)
            // sha256_prefix covers the PLAINTEXT, so it is an integrity check after
            // decryption -- and not a MAC.
            val body = dat.copyOfRange(WalletFormat.ASSET_HEADER_LEN, dat.size)
            val plainPrefix = sha256(cipher().open(pi.assetId,
                dat.copyOfRange(0, WalletFormat.ASSET_HEADER_LEN), body)).substring(0, 16)
            assertEquals(plainPrefix,
                WalletFormat.hex(dat.copyOfRange(24, 32)))
            assertNull("no sidecar on an encrypted tree", sink.rle[pi.assetId])
        }
    }

    @Test
    fun the_manifest_says_which_scheme_encrypted_it() {
        val (item, _) = fx.build(cipher())
        val wallet = Wallet.fromManifestJson(fx.ourManifest(item))
        assertEquals(ManifestKind.ENCRYPTED, wallet.manifestKind)
        assertEquals(WalletFormat.MANIFEST_ENC_NAME, wallet.manifestFileName)
        assertEquals("wallet-crypto-v1", Json.asString(wallet.crypto!!["scheme"]))
        assertEquals("aes-256-ctr", Json.asString(wallet.crypto!!["assets"]))
        assertEquals("aes-256-gcm", Json.asString(wallet.crypto!!["manifest"]))
    }

    @Test
    fun the_key_file_the_fixture_ships_is_the_key_the_files_json_records() {
        assertEquals(fx.keyHex!!.trim(), text(fx.dir, "key.hex").trim())
    }
}
