package org.explorink.gpsbridge.wallet

import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertTrue
import org.junit.Test
import java.io.ByteArrayOutputStream
import java.io.InputStream
import java.security.MessageDigest
import java.util.zip.GZIPInputStream

/**
 * **The check this whole phase rests on: the Kotlin pipeline must produce the
 * same bytes as `tools/walletgen.py`.**
 *
 * The app cannot be verified the usual way -- there is no device-side viewer here
 * and no way to look at an asset -- so parity against the reference implementation
 * is the evidence. Fixtures under `src/test/resources/`, regenerated by
 * `tools/wallet_parity_fixture.py`, one directory per generator configuration:
 *
 *     wallet-parity/        the DEFAULT output: page images, no pre-cut tiles
 *     wallet-parity-tiles/  --tiles, the pre-design-B shape
 *     wallet-parity-grey/   --grey, the per-document four-level grey assets
 *     wallet-parity-enc/    --key (checked by `WalletCryptoParityTest`)
 *
 * Each holds `files.json` (per-file size, sha256 and 32-byte header, plus the run
 * parameters) and the manifest verbatim. The input page lives once, in
 * `wallet-parity/`:
 *
 *     demo-a4.png       the input page: `walletgen.py --demo`, for a human
 *     demo-a4.gray.gz   the same page's raw 8-bit grey pixels, gzipped
 *
 * The page is committed rather than regenerated because it is the **input**, and
 * its text is rasterised by whatever font happens to be installed -- not
 * reproducible across machines, and not part of the pipeline. Both sides then
 * consume identical pixels, which `graySha256` proves before anything else runs.
 *
 * The test reads the raw pixels, not the PNG: `javax.imageio` is not on the
 * Android unit-test compile classpath (`android.jar` shadows the JDK's
 * `java.desktop`), and a PNG decoder written for a test would be one more thing
 * that can be wrong.
 *
 * What this covers: autocontrast, the Lanczos resize at all three zoom levels,
 * Floyd-Steinberg dither, tile slicing, the native rotation, 1bpp packing, the
 * 32-byte header, the RLE sidecar, the asset and item id recipes, the page-image
 * geometry, the grey assets, and `manifest.json` as text.
 *
 * What it cannot cover, because there is no phone here: the decode of a real
 * JPEG, EXIF orientation off a camera, the share target, and the UI. Those are
 * emulator work -- `docs/android-wallet.md` says which were exercised and how.
 */
class WalletParityTest {

    companion object {
        const val DEFAULT = "wallet-parity"
        const val TILES = "wallet-parity-tiles"
        const val GREY = "wallet-parity-grey"

        /**
         * `--grey --tone photo`: the same grey assets by error diffusion.
         *
         * Its own fixture because the diffusion rounds in code rather than through a
         * table, and the two languages disagree by default -- Kotlin's `/` truncates
         * toward zero, Python's `//` floors, so `-9/16` is 0 on one side and -1 on the
         * other. One pixel of disagreement is a different asset id and a wallet the
         * device cannot match.
         */
        const val PHOTO = "wallet-parity-photo"

        /** Where the shared input page lives. */
        const val INPUT = "wallet-parity"

        fun stream(dir: String, name: String): InputStream =
            WalletParityTest::class.java.classLoader!!.getResourceAsStream("$dir/$name")
                ?: throw AssertionError("missing fixture $dir/$name " +
                    "(regenerate with tools/wallet_parity_fixture.py)")

        fun bytes(dir: String, name: String): ByteArray = stream(dir, name).use { it.readAll() }

        fun text(dir: String, name: String): String = bytes(dir, name).toString(Charsets.UTF_8)

        fun sha256(b: ByteArray): String =
            WalletFormat.hex(MessageDigest.getInstance("SHA-256").digest(b))

        fun InputStream.readAll(): ByteArray {
            val out = ByteArrayOutputStream()
            val buf = ByteArray(8192)
            while (true) {
                val n = read(buf)
                if (n < 0) break
                out.write(buf, 0, n)
            }
            return out.toByteArray()
        }

        /** Everything one fixture directory recorded about its generator run. */
        class Fixture(val dir: String) {
            private val meta = Json.asMap(Json.parse(text(dir, "files.json")))
            val run = Json.asMap(meta["run"])
            val source = Json.asMap(meta["source"])
            val manifestName = Json.asString(meta["manifest"])
            val manifestSha256 = Json.asString(meta["manifestSha256"])
            val keyHex: String? = meta["keyHex"] as String?
            val files = Json.asList(meta["files"]).map { Json.asMap(it) }

            val panel: PanelProfile get() = Panels.byName(Json.asString(run["panel"]))
            val title: String get() = Json.asString(run["title"])
            val sourceName: String get() = Json.asString(source["file"])
            val tiles: Boolean get() = run["tiles"] == true
            val grey: Boolean get() = run["grey"] == true
            val tone: WalletPipeline.Tone
                get() = WalletPipeline.Tone.of(run["tone"] as String?)
            val encrypted: Boolean get() = run["encrypted"] == true

            /** The fixture page, as the grayscale raster both implementations start from. */
            fun page(): GrayImage {
                val w = Json.asInt(source["width"])
                val h = Json.asInt(source["height"])
                val px = GZIPInputStream(stream(INPUT, Json.asString(source["gray"]))).use {
                    it.readAll()
                }
                assertEquals("fixture pixel count", w * h, px.size)
                return GrayImage(w, h, px)
            }

            fun manifestText(): String = text(dir, manifestName)

            /**
             * Build the same item the generator built, in memory.
             *
             * Note what is NOT passed in: no expected geometry, no tile counts, no ids.
             * Only the panel, the flags the run recorded, the title, the source name and
             * the timestamp -- everything else is derived, which is the point.
             */
            fun build(cipher: AssetCipher = AssetCipher.None): Pair<WalletItem, MemoryAssetSink> {
                val sink = MemoryAssetSink()
                val pipeline = WalletPipeline(panel, pageImage = run["pageImage"] == true,
                    tiles = tiles, grey = grey, tone = tone, cipher = cipher)
                val item = pipeline.buildItem(
                    itemId = WalletFormat.itemIdFor(title, listOf(sourceName)),
                    title = title,
                    createdAt = Json.asString(run["createdAt"]),
                    sortOrder = 0,
                    sources = listOf(WalletPipeline.PageSource(
                        gray = page(),
                        name = sourceName,
                        dpiX = source["dpiX"] as Double?,
                        dpiY = source["dpiY"] as Double?,
                    )),
                    sink = sink,
                    paper = Json.asString(run["paper"]),
                    version = Json.asInt(run["version"]),
                )
                return Pair(item, sink)
            }

            /** The manifest we would write for this run. */
            fun ourManifest(item: WalletItem): String = Wallet(
                formatVersion = WalletFormat.MANIFEST_FORMAT_VERSION,
                walletVersion = 1,
                panelName = panel.name,
                items = listOf(item),
                crypto = if (encrypted) WalletCrypto.descriptor() else null,
            ).toManifestJson()

            fun datCount(): Int = files.count { Json.asString(it["path"]).endsWith(".dat") }
            fun rleCount(): Int = files.count { Json.asString(it["path"]).endsWith(".rle") }
            fun datBytes(): Long = files.filter { Json.asString(it["path"]).endsWith(".dat") }
                .sumOf { Json.asInt(it["size"]).toLong() }
        }
    }

    // --- the input ---------------------------------------------------------

    @Test
    fun the_fixture_page_is_the_pixels_the_generator_saw() {
        // If this fails, nothing below means anything: the two sides are looking
        // at different images and any divergence is the fixture's, not the code's.
        val fx = Fixture(DEFAULT)
        val page = fx.page()
        assertEquals(Json.asInt(fx.source["width"]), page.width)
        assertEquals(Json.asInt(fx.source["height"]), page.height)
        assertEquals(Json.asString(fx.source["graySha256"]), sha256(page.pixels))
    }

    // --- ids ---------------------------------------------------------------

    @Test
    fun the_item_id_recipe_agrees() {
        val fx = Fixture(DEFAULT)
        val expected = Wallet.fromManifestJson(fx.manifestText()).items[0].id
        assertEquals(expected, WalletFormat.itemIdFor(fx.title, listOf(fx.sourceName)))
    }

    @Test
    fun auto_paper_picks_what_the_generator_picked() {
        val fx = Fixture(DEFAULT)
        val page = fx.page()
        val expected = Wallet.fromManifestJson(fx.manifestText()).items[0].pages[0].paper
        assertEquals(expected, WalletFormat.pickPaper(page.width, page.height,
            fx.source["dpiX"] as Double?, fx.source["dpiY"] as Double?))
    }

    // --- the assets --------------------------------------------------------

    /** Every recorded file, byte for byte, for one fixture directory. */
    private fun assertEveryFileMatches(fx: Fixture) {
        val (_, sink) = fx.build()
        var checkedDat = 0
        var checkedRle = 0
        for (f in fx.files) {
            val path = Json.asString(f["path"])
            val assetId = path.substringAfterLast('/').substringBeforeLast('.')
            val ext = path.substringAfterLast('.')
            val ours = (if (ext == "dat") sink.dat[assetId] else sink.rle[assetId])
            assertNotNull("${fx.dir}: we never produced $path", ours)
            assertEquals("$path shard", WalletFormat.shardOf(assetId), path.substringBefore('/'))
            assertEquals("$path size", Json.asInt(f["size"]), ours!!.size)
            assertEquals("$path header", Json.asString(f["header"]),
                WalletFormat.hex(ours.copyOfRange(0, WalletFormat.ASSET_HEADER_LEN)))
            assertEquals("$path sha256", Json.asString(f["sha256"]), sha256(ours))
            if (ext == "dat") checkedDat++ else checkedRle++
        }
        assertEquals("${fx.dir} .dat count", fx.datCount(), checkedDat)
        assertEquals("${fx.dir} .rle count", fx.rleCount(), checkedRle)
        assertEquals("${fx.dir}: we produced assets the generator did not",
            checkedDat, sink.dat.size)
    }

    @Test
    fun every_asset_file_is_byte_identical() {
        assertEveryFileMatches(Fixture(DEFAULT))
    }

    @Test
    fun every_asset_file_is_byte_identical_with_tiles() {
        assertEveryFileMatches(Fixture(TILES))
    }

    @Test
    fun every_asset_file_is_byte_identical_for_a_grey_document() {
        assertEveryFileMatches(Fixture(GREY))
    }

    @Test
    fun every_asset_file_is_byte_identical_for_a_photograph() {
        // The check that catches a rounding difference in the error diffusion, which is
        // the one part of the grey path written twice as arithmetic rather than shared
        // as a table.
        assertEveryFileMatches(Fixture(PHOTO))
    }

    @Test
    fun the_photo_tone_actually_produced_different_bytes_than_the_document_tone() {
        // Otherwise the test above passes by drawing the same thing twice, which is how
        // a "parity" suite ends up proving nothing.
        val grey = Fixture(GREY)
        val photo = Fixture(PHOTO)
        val greyIds = grey.files.map { Json.asString(it["sha256"]) }.toSet()
        val photoIds = photo.files.map { Json.asString(it["sha256"]) }.toSet()
        assertTrue("the two fixtures are the same bytes: diffusion did nothing",
            (greyIds - photoIds).isNotEmpty())
    }

    /**
     * **The default output is page images only.** Three assets a page, one per zoom
     * level, and not one pre-cut tile.
     *
     * That is not a size optimisation dressed as a design: design B needs the whole
     * page because the device pans by a fraction of a view, which pre-cut tiles cannot
     * express (`docs/wallet-plan.md` 7a). Before this default the phone shipped 24
     * assets a page and the device panned with none of the 21 tiles among them.
     */
    @Test
    fun the_default_output_is_three_page_images_and_no_tiles() {
        val fx = Fixture(DEFAULT)
        assertFalse("the default fixture must be built without --tiles", fx.tiles)
        assertEquals(3, fx.datCount())
        val (item, sink) = fx.build()
        assertEquals(3, sink.dat.size)
        assertEquals(3, item.assetCount)
        for (name in WalletFormat.LEVELS) {
            val level = item.pages[0].levels.getValue(name)
            assertNotNull("level $name has a page image", level.pageImage)
            assertEquals("level $name has no tiles", 0, level.assets.size)
            // The grid is still described, because it is what the focal hint and the
            // 1:1 arithmetic are expressed in -- it just has no assets under it.
            assertTrue("level $name still states its grid", level.cols > 0 && level.rows > 0)
        }
    }

    /**
     * The size the default buys, measured off the two fixtures rather than asserted
     * from a doc: 24 assets against 3, and 1.83 MB of `.dat` against 826 kB.
     */
    @Test
    fun dropping_the_tiles_is_the_bulk_of_the_bytes() {
        val plain = Fixture(DEFAULT)
        val tiled = Fixture(TILES)
        assertEquals(3, plain.datCount())
        assertEquals(24, tiled.datCount())
        assertEquals(825_814L, plain.datBytes())
        assertEquals(1_834_486L, tiled.datBytes())
        // The page images are the same three assets in both trees: dropping the tiles
        // removes assets, it does not change the ones the device actually reads.
        val plainPaths = plain.files.map { Json.asString(it["path"]) }.toSet()
        assertTrue("the tiled tree contains every default asset",
            tiled.files.map { Json.asString(it["path"]) }.containsAll(plainPaths))
    }

    // --- the manifest ------------------------------------------------------

    @Test
    fun the_manifest_is_byte_identical_as_text() {
        for (dir in listOf(DEFAULT, TILES, GREY)) {
            val fx = Fixture(dir)
            val (item, _) = fx.build()
            val ours = fx.ourManifest(item)
            assertEquals("$dir manifest", fx.manifestText(), ours)
            assertEquals("$dir manifest sha256", fx.manifestSha256,
                sha256(ours.toByteArray(Charsets.UTF_8)))
        }
    }

    @Test
    fun the_manifest_survives_a_round_trip_through_our_own_parser() {
        for (dir in listOf(DEFAULT, TILES, GREY)) {
            val theirs = Fixture(dir).manifestText()
            assertEquals(dir, theirs, Wallet.fromManifestJson(theirs).toManifestJson())
        }
    }

    /**
     * A cleartext tree says `"crypto": null` -- the key is present and empty, not
     * absent. The generator writes it that way on every tree, so a manifest compared
     * as text has to as well.
     */
    @Test
    fun a_cleartext_manifest_still_carries_the_crypto_key() {
        val theirs = Fixture(DEFAULT).manifestText()
        assertTrue(theirs.contains("\"crypto\": null"))
        val wallet = Wallet.fromManifestJson(theirs)
        assertEquals(null, wallet.crypto)
        assertEquals(ManifestKind.CLEARTEXT, wallet.manifestKind)
        assertEquals(WalletFormat.MANIFEST_CLEAR_NAME, wallet.manifestFileName)
    }

    @Test
    fun the_sidecars_decode_back_to_the_payloads() {
        // Parity says the bytes match. This says they are also *correct*: the
        // device rebuilds a .dat out of the sidecar alone, so the sidecar has to
        // carry the payload and the header, not merely the right number of bytes.
        val fx = Fixture(TILES)
        val (_, sink) = fx.build()
        for ((assetId, rle) in sink.rle) {
            val dat = sink.dat.getValue(assetId)
            val header = rle.copyOfRange(0, WalletFormat.ASSET_HEADER_LEN)
            assertEquals("$assetId header prefix",
                WalletFormat.hex(dat.copyOfRange(0, WalletFormat.ASSET_HEADER_LEN)),
                WalletFormat.hex(header))
            val payload = Rle.decode(rle.copyOfRange(WalletFormat.ASSET_HEADER_LEN, rle.size))
            assertEquals("$assetId payload length",
                dat.size - WalletFormat.ASSET_HEADER_LEN, payload.size)
            assertEquals("$assetId payload",
                sha256(dat.copyOfRange(WalletFormat.ASSET_HEADER_LEN, dat.size)),
                sha256(payload))
        }
    }

    @Test
    fun a_tile_aligned_window_of_the_page_image_is_the_tile() {
        // The page image and the tiles come out of the same dithered bitmap, so a
        // window pulled at a tile origin must equal the pre-cut tile. If this fails
        // the two outputs disagree with each other, whatever the parity says. Run
        // against the --tiles fixture, because the default one has no tiles to compare.
        val fx = Fixture(TILES)
        val (item, sink) = fx.build()
        val panel = fx.panel
        val level = item.pages[0].levels.getValue("one_to_one")
        val pi = level.pageImage!!
        val page = sink.dat.getValue(pi.assetId)
            .copyOfRange(WalletFormat.ASSET_HEADER_LEN, WalletFormat.ASSET_HEADER_LEN + pi.rawLen)

        val pipeline = WalletPipeline(panel)
        var compared = 0
        for (tile in level.assets) {
            val (x, y) = pipeline.tileWindowOrigin(tile.col, tile.row, pi.nativeHeight)
            if (x < 0 || y < 0) continue
            if (x + panel.width > pi.nativeWidth || y + panel.height > pi.nativeHeight) continue
            val window = ByteArray(panel.assetBytes)
            for (row in 0 until panel.height) {
                System.arraycopy(page, (y + row) * pi.rowBytes + x / 8,
                    window, row * panel.rowBytes, panel.rowBytes)
            }
            assertEquals("tile (${tile.col},${tile.row})", tile.sha256, sha256(window))
            compared++
        }
        // 9 of the 16 A4 1:1 tiles lie fully inside the page extent; the rest are
        // in the white padding a page image drops.
        assertEquals(9, compared)
    }

    @Test
    fun the_page_image_geometry_matches_the_manifest() {
        val fx = Fixture(DEFAULT)
        val (item, _) = fx.build()
        val theirs = Wallet.fromManifestJson(fx.manifestText()).items[0]
        for (name in WalletFormat.LEVELS) {
            val a = item.pages[0].levels.getValue(name).pageImage
            val b = theirs.pages[0].levels.getValue(name).pageImage
            assertEquals("level $name has a page image", b != null, a != null)
            assertEquals("level $name", b, a)
        }
    }

    /**
     * **The grey entries speak the page image's vocabulary, against the generator.**
     *
     * The field-name mismatch this pins cost a whole hardware round on the generator
     * side: the byte layouts agreed, the key names did not, the firmware's one struct
     * parsed the entry as present-but-zero, and `grey_rendered=0` was the only symptom
     * (`docs/wallet-plan.md` 7j). Comparing key-for-key against the generator's own
     * manifest is the check that cannot drift.
     */
    @Test
    fun the_grey_entries_carry_the_generators_own_field_names() {
        val fx = Fixture(GREY)
        val (item, _) = fx.build()
        val theirs = Wallet.fromManifestJson(fx.manifestText()).items[0]
        val imageVocabulary = listOf("nativeWidth", "nativeHeight", "rowBytes", "rawLen",
            "windowStepX", "windowStepY", "focalX", "focalY")
        for (name in WalletFormat.LEVELS) {
            val ours = item.pages[0].levels.getValue(name)
            val gen = theirs.pages[0].levels.getValue(name)
            for (which in listOf("greyPageImage", "greyPlanes")) {
                val a = (if (which == "greyPageImage") ours.greyPageImage else ours.greyPlanes)!!
                val b = (if (which == "greyPageImage") gen.greyPageImage else gen.greyPlanes)!!
                assertEquals("$name $which key order", b.fields.keys.toList(),
                    a.fields.keys.toList())
                for (k in imageVocabulary) {
                    assertTrue("$name $which is missing $k", a.fields.containsKey(k))
                    assertEquals("$name $which $k", Json.asInt(b.fields[k]),
                        Json.asInt(a.fields[k]))
                }
            }
        }
    }

    @Test
    fun a_wrong_pipeline_would_fail_this_test() {
        // A parity check that cannot fail is worth nothing. Break one step -- skip
        // autocontrast -- and the page image must stop matching.
        val fx = Fixture(DEFAULT)
        val panel = fx.panel
        val pipeline = WalletPipeline(panel)
        val mono = pipeline.levelCanvas(fx.page(), "fit", "a4").dither()
        val wrong = mono.packNativeRegion(0, 0, panel.tileW, panel.tileH)
        val right = Wallet.fromManifestJson(fx.manifestText())
            .items[0].pages[0].levels.getValue("fit").pageImage!!.sha256
        assertTrue("skipping autocontrast must change the bytes", sha256(wrong) != right)
    }
}
